### ISSUE TITLE
feat: add basic performance profiling

### ISSUE THREAD

**Issue by t-bre** [sufst/on-car-telemetry#10]
### Description
Add some simple runtime profiling to gather information on:

- Received CAN messages (count).
- Received CAN data (bits/s over some recent time period). 
- Transmitted telemetry PDUs (count).
- Transmitted telemetry PDU data (bits/s over some recent time period).

Received CAN data could be calculated by summing DLCs of received CAN messages. Transmitted data could be calculated by summing the size of the packed PDU data for each PDU transmitted. In both cases, it might be good to add the header size to the calculation too.

This information should allow us to determine how much of the wireless bandwidth we are using.

### Future Work

As a future development, this information could then be broadcast periodically on the CAN-S (non critical systems) bus for logging by the datalogger.

**Comment by rureverek** [comment]
I want to implement a timer with a callback function that update bits/s rate. What do you think about such implementation? Should I use software or hardware timer?

**Comment by t-bre** [comment]
I would go with a ThreadX software timer, then you can do a quick calculation in the callback function using the current timestamp.

**Comment by t-bre** [comment]
Of course you'll also need to update the number of bits every time a CAN message comes in or a PDU is transmitted, so maybe the calculation can be done there in some way instead. Up to you really.
