### ISSUE TITLE
feat: add debugging mode and `config.h` file

### ISSUE THREAD

**Issue by rureverek** [sufst/on-car-telemetry#13]
### Description
Create config.h to implement two modes of operation: DEBUG and NORMAL mode. DEBUG mode will read data from LUT  (#7) and NORMAL mode will use CAN interface (#8).

### Requirements

- [ ] `config.h` contain definitions of two modes
- [ ] Source files must take in account the mode to compile the right piece of code

### Note
This should be done after completion of #8 and #7

**Comment by RyutaItabashi** [comment]
FY(my)I : https://github.com/sufst/vcu/blob/develop/src/SUFST/Inc/config.h
