### ISSUE TITLE
feat: interface with XBee in API mode

### ISSUE THREAD

**Issue by t-bre** [sufst/on-car-telemetry#32]
### Description
The intermediate server requires the XBee's to be configured in API mode. At the moment (for testing), the XBees are configured to operate in transparent mode. Since transparent mode has been shown to work in testing, we can now take the next step to running in API mode.

### Additional Notes
This will require the STM32 port of the XBee library in [https://github.com/sufst/xbee_ansic_library](https://github.com/sufst/xbee_ansic_library) to be finished / tested.

**Comment by rureverek** [comment]
Created branch [feat/add_api_mode](https://github.com/sufst/on-car-telemetry/tree/feat/add_api_mode). If you wish to contribute, see todo comments @RyutaItabashi.
