### ISSUE TITLE
feat: read CAN example data from local file

### ISSUE THREAD

**Issue by RyutaItabashi** [sufst/on-car-telemetry#7]
### Description
In can_publisher.c we currently make can data example of [0,1,2,3,4…]but change this to read from local file

**Comment by t-bre** [comment]
What kind of file would this be read from and how will we create it?

**Comment by RyutaItabashi** [comment]
Initiial plan was to include one csv file but figured out that won't work so we will use some global config header file to declare if we use test data or not and write the actual dummy data in header files

**Comment by RyutaItabashi** [comment]
-> https://github.com/sufst/on-car-telemetry/issues/13
